all:
	g++ -o 01-compress 01-compress.cpp
	g++ -o 02-decompress 02-decompress.cpp
	g++ -o 03-forkcompress 03-forkcompress.cpp
	g++ -o 04-pipecompress 04-pipecompress.cpp
	g++ -o 05-parfork 05-parfork.cpp
	g++ -o 06-minishel 06-minishell.cpp
	g++ -o 07-moreshell 07-moreshell.cpp
	g++ -o 08-dupshell 08-dupshell.cpp
	g++ -o 09-parthread 09-parthread.cpp